# Target file name (without extension).
TARGET = kimera_zero

# Directory common source filess exist
TMK_DIR = ../../tmk_core_custom

# Directory keyboard dependent files exist
TARGET_DIR = .

# project specific files
SRC =	keymap_common.c \
	matrix.c \
	led.c

ifdef KEYMAP
    SRC := keymap_$(KEYMAP).c $(SRC)
else
    SRC := keymap_default.c $(SRC)
endif


CONFIG_H = config.h

include $(TMK_DIR)/tool/samd/rules.mk
include $(TMK_DIR)/tool/samd/common.mk
